tstellar/llvm-project

.github/workflows/main.yml

Test action

---

llvm/lib/CodeGen/SelectionDAG/FastISel.cpp
llvm/test/CodeGen/X86/sink-local-value.ll

phi inserted before landingpad by GCOVProfiling causes incorrect code generation

---

clang/lib/Sema/TreeTransform.h
clang/test/SemaTemplate/subst-into-subst.cpp

Please merge b20ab412bf838a8a87e5cc1c8c6399c3c9255354 to release/10.x

---

llvm/lib/Transforms/Scalar/SimplifyCFGPass.cpp
llvm/test/Transforms/SimplifyCFG/callbr-destinations.ll

Please merge c2dafe12dc24f7f1326f5c4c6a3b23f1485f1bd6 into release/10.x

---

lld/test/COFF/pdb-tpi-aligned-records.test
llvm/include/llvm/DebugInfo/CodeView/GlobalTypeTableBuilder.h
llvm/lib/DebugInfo/CodeView/MergingTypeTableBuilder.cpp
llvm/lib/DebugInfo/CodeView/TypeStreamMerger.cpp
llvm/lib/DebugInfo/PDB/Native/TpiStreamBuilder.cpp

Please merge a7325298e1f311b383b8ce5ba8e2d3698fef472a to release/10.x

---

llvm/lib/Transforms/Coroutines/CoroSplit.cpp
llvm/test/Transforms/Coroutines/no-suspend.ll

Merge 032251e34d17c1cbf21e7571514bb775ed5cdf30 into the 10.0 branch :

---

.github/workflows/libclc-tests.yml
libclc/CMakeLists.txt

Please merge 814fb658ca262f5c2df47f11d47f91fac188e0d6 to 10.0

---

llvm/lib/Target/BPF/BPFMISimplifyPatchable.cpp
llvm/test/CodeGen/BPF/CORE/store-addr.ll

backport 3cb7e7bf959dcd3b8080986c62e10a75c7af43f0 to 10.0.1

---

clang/include/clang/AST/DeclBase.h
clang/lib/AST/DeclBase.cpp
clang/lib/Sema/SemaTemplateInstantiate.cpp
clang/lib/Sema/SemaTemplateInstantiateDecl.cpp
clang/lib/Sema/TreeTransform.h
clang/test/SemaCXX/vartemplate-lambda.cpp
clang/test/SemaTemplate/instantiate-local-class.cpp

In CodeGen::CodeGenFunction::EmitCallArgs: Assertion `[...] && "type mismatch in call argument!"' failed

---

clang/tools/libclang/CMakeLists.txt

libclang has no registered targets after r371787

---

clang/lib/Format/TokenAnnotator.cpp
clang/unittests/Format/FormatTest.cpp

clang-format: unexpected change on operator

---

clang/lib/Driver/ToolChains/Darwin.cpp
compiler-rt/lib/profile/GCDAProfiling.c
compiler-rt/test/profile/Inputs/instrprof-gcov-multithread_fork.cpp
compiler-rt/test/profile/instrprof-gcov-multithread_fork.test
llvm/lib/Transforms/Instrumentation/GCOVProfiling.cpp

Dead lock when forking with coverage enabled in multithreaded environment

---

clang/lib/CodeGen/CodeGenModule.cpp
clang/test/CodeGen/memcpy-no-nobuiltin-if-not-emitted.c
clang/test/CodeGen/memcpy-no-nobuiltin-if-not-emitted.cpp

excessive stack usage for FORTIFY_SOURCE building the kernel

---

llvm/lib/Target/X86/X86IndirectBranchTracking.cpp
llvm/lib/Target/X86/X86TargetMachine.cpp
llvm/lib/Target/X86/X86TargetMachine.h
llvm/test/CodeGen/X86/indirect-branch-tracking-cm-lager.ll
llvm/test/CodeGen/X86/indirect-branch-tracking-eh.ll

Hjl/cet/llvmorg 10.0.0

---

clang/lib/AST/RawCommentList.cpp

Backport ad7211df6f257e39da2e5a11b2456b4488f32a1e to 10.0.1

---

llvm/lib/MC/MCObjectFileInfo.cpp

Please merge 2504f14a06872f2e1755a88b3aab7e6bc280bec7 to 10.0.1

---

llvm/lib/Target/ARM/ARMISelLowering.cpp
llvm/test/CodeGen/ARM/sadd_sat.ll

[arm] Merge 8807139026b6 into 10.0.1

---

llvm/lib/Target/ARM/MCTargetDesc/ARMAsmBackend.cpp
llvm/test/MC/ARM/pcrel-global.s

[ARM] Merge fc373522b044 into 10.0.1

---

llvm/lib/CodeGen/BranchFolding.cpp
llvm/test/CodeGen/X86/branchfolding-ehpad.mir

Wrong jump destination with -O2 -fexperimental-new-pass-manager

---

llvm/lib/Target/X86/X86ISelLowering.cpp
llvm/test/CodeGen/X86/vec_shift5.ll

Merge 7c9a89fed8f5d53d61fe3a61a2581a7c28b1b6d2 and 3408dcbdf054ac3cc32a97a6a82a3cf5844be609 to 10.0.1

---

llvm/lib/Target/AArch64/AArch64BranchTargets.cpp
llvm/test/CodeGen/AArch64/branch-target-enforcement.mir

Merge b8ae3fdfa579dbf366b1bb1cbfdbf8c51db7fa55 into the 10.0.1

---

llvm/lib/Target/X86/X86InstrInfo.cpp
llvm/test/CodeGen/X86/materialize.ll

Backport ece79f47083babcabde3700c67b90ef19967a5b3 for 10.0.1

---

clang/lib/Basic/Targets/PPC.h
clang/test/CodeGen/ppc64-inline-asm.c

unexpected codegen for inline asm

---

llvm/lib/LTO/LTO.cpp

Merge 252892fea7088abbeff9476e0ecbacc091d135a0 into the 10.0 branch

---

llvm/lib/Target/BPF/BTFDebug.cpp
llvm/test/CodeGen/BPF/BTF/pruning-const.ll
llvm/test/CodeGen/BPF/BTF/pruning-typedef.ll

backport 89648eb16d01725457f958e634d16c534b64c42c

---

clang-tools-extra/clangd/FindSymbols.cpp
clang-tools-extra/clangd/unittests/FindSymbolsTests.cpp

Cherry-pick fb3d9153c01b9a560680465190d6ecd804e4c486 into 10.0.1 release

---

clang/lib/Basic/CMakeLists.txt
lld/Common/CMakeLists.txt
lldb/source/CMakeLists.txt
llvm/cmake/modules/LLVMConfig.cmake.in
llvm/docs/CMake.rst

Add "Make LLVM_APPEND_VC_REV=OFF affect > clang, lld, and lldb as well." for 10.0.1 release

---

llvm/lib/Target/BPF/BPFISelDAGToDAG.cpp
llvm/test/CodeGen/BPF/rodata_5.ll

backport 4db1878158a3f481ff673fef2396c12b7a53d280

---

clang/lib/Driver/SanitizerArgs.cpp
clang/lib/Driver/ToolChain.cpp
clang/test/Driver/fsanitize.c

arm64be fails with -fsanitize=shadow-call-stack

---

llvm/lib/Target/AArch64/AArch64FrameLowering.cpp
llvm/test/CodeGen/AArch64/funclet-match-add-sub-stack.ll
llvm/test/CodeGen/AArch64/seh-finally.ll
llvm/test/CodeGen/AArch64/wineh-try-catch-cbz.ll
llvm/test/CodeGen/AArch64/wineh-try-catch-realign.ll
llvm/test/CodeGen/AArch64/wineh-try-catch.ll
llvm/test/CodeGen/AArch64/wineh-unwindhelp-via-fp.ll

Backport AArch64 on Windows fixes for 10.0.1

---

libcxx/include/array

r372359 causes stack overflow parsing large array

---

llvm/lib/IR/ConstantFold.cpp
llvm/test/Assembler/ConstantExprNoFold.ll
llvm/test/Transforms/InstCombine/2010-03-03-ExtElim.ll

icmp gives inconsistent result for unnamed functions

---

llvm/lib/Target/BPF/BPFISelDAGToDAG.cpp
llvm/test/CodeGen/BPF/rodata_6.ll
llvm/test/CodeGen/BPF/rodata_7.ll

BPF: backport commit 31611721686760fe59c91a84b025e4dee94d1662

---

lld/ELF/LinkerScript.cpp
lld/test/ELF/linkorder-mixed2.s

Merge ae73091f30245852817c5c0af050a5a731dee50a into 11.0.1

---

llvm/utils/release/export.sh

Provide tarballs for libclc alongside LLVM releases

---

llvm/lib/Support/Host.cpp

Merge 0d17dc2e75428885e37e53a1524ce7b607501cfa to 11.0.1

---

clang/lib/Sema/SemaExpr.cpp
clang/test/SemaTemplate/pr47676.cpp

Assertion failed: (isScalarType()), function getScalarTypeKind, file /usr/src/contrib/llvm-project/clang/lib/AST/Type.cpp, line 2146.

---

clang/lib/Sema/UsedDeclVisitor.h

Please merge b9225543e844bee5091aa16108e0c54bd2abe485 to 11.x

---

llvm/include/llvm/Transforms/IPO/DeadArgumentElimination.h
llvm/lib/Transforms/IPO/DeadArgumentElimination.cpp
llvm/test/Transforms/DeadArgElim/preserve-used-ret.ll

DeadArgumentEliminationPass eliminates live return value

---

clang/examples/Attribute/CMakeLists.txt

Please merge 04ea680a8ccc4f9a4d7333cd712333960348c35b to 11.x

---

llvm/include/llvm/ADT/ImmutableMap.h
llvm/unittests/ADT/ImmutableMapTest.cpp

Merge 184eb4fa4f1cc871692fa390261df8c25ddcc7ec into 11.0.1: [ADT] Fix for ImmutableMapRef

---

clang/include/clang/Basic/Attr.td
clang/include/clang/Basic/AttrDocs.td
clang/lib/Sema/SemaDeclAttr.cpp
clang/test/SemaCXX/init-priority-attr.cpp

Please merge af1d3e655991e5f0c86df372b8583a60d20268e0 to 11.x

---

clang/include/clang/Basic/DiagnosticDriverKinds.td
clang/lib/Driver/ToolChains/Cuda.cpp
clang/lib/Driver/ToolChains/Cuda.h
clang/test/Driver/Inputs/CUDA_102/usr/local/cuda/version.txt
clang/test/Driver/Inputs/CUDA_111/usr/local/cuda/include/cuda.h
clang/test/Driver/cuda-version-check.cu

Please cherry-pick CUDA fixes for PR47332 into 11.0.1 and 10.0.2

---

llvm/lib/Target/X86/X86ISelLowering.cpp
llvm/test/CodeGen/X86/avx512-select.ll

backport c58674df147ac0e to 11.0

---

llvm/lib/ExecutionEngine/RuntimeDyld/RuntimeDyld.cpp

Bacport 85f4be09124cc53e1a18a884ac7caf19988ab2a5 tor 11.0

---

clang/lib/Headers/__clang_cuda_complex_builtins.h
clang/lib/Headers/openmp_wrappers/complex
clang/lib/Headers/openmp_wrappers/complex.h

Using both -x cuda and -fopenmp complex wrappers block compilation

---

clang/lib/Format/FormatToken.h
clang/lib/Format/UnwrappedLineParser.cpp
clang/lib/Format/WhitespaceManager.cpp
clang/unittests/Format/FormatTest.cpp
clang/unittests/Format/FormatTestComments.cpp

Revert "[clang-format] Fix AlignConsecutive on PP blocks"

---

llvm/lib/DebugInfo/DWARF/DWARFUnitIndex.cpp
llvm/test/tools/llvm-symbolizer/split-dwarf-zero-signature-not-found.s

Please cherry-pick 314a0d73a844 (Fix crash after looking up dwo_id=0 in CU index) into 11.0.1

---

llvm/lib/Target/WebAssembly/WebAssemblyInstrInfo.td
llvm/lib/Target/WebAssembly/WebAssemblyRegisterInfo.cpp
llvm/test/CodeGen/WebAssembly/userstack.ll

Merge 0fca6517118d435f9c2d7afe6135fd5f357509b5 into 11.0.1 release

---

clang/test/Driver/hip-toolchain-rdc-static-lib.hip
clang/test/Driver/hip-toolchain-rdc.hip

Driver/hip-toolchain-rdc-static-lib.hip fails on Windows

---

clang/lib/CodeGen/CGObjCGNU.cpp
clang/test/CodeGenObjC/gnu-method-only-once.m

Method metadata emitted twice from synthesised properties targeting GNU Objective-C runtimes

---

llvm/lib/MC/MCObjectFileInfo.cpp
llvm/test/MC/AArch64/ELF_ARM64_large-relocations.s

Backport 18805ea951be to 11.0

---

clang/lib/CodeGen/TargetInfo.cpp
clang/test/CodeGen/riscv32-ilp32d-abi.cpp

Backport RISC-V ABI fix

---

clang/lib/Headers/cuda_wrappers/new

Clang fails to compile cuda code in C++20 mode, works in C++17

---

llvm/lib/Target/Sparc/SparcAsmPrinter.cpp
llvm/test/CodeGen/SPARC/inlineasm-v9.ll

Merge 9ae95a0f8f1bc9bd9e8eb30a5a9444fbdca5cc29 into 11.0.1

---

llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp
llvm/test/Transforms/InstCombine/saturating-add-sub.ll

[InstCombine] Miscompile, improper substitution of uadd.sat

---

clang/test/CodeGen/asan-globals-alias.cpp
llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp

Please pick c28b18af19621e6b5cca257ef7139ba93833df0c to release/11.x

---

llvm/lib/Target/AArch64/GISel/AArch64InstructionSelector.cpp
llvm/test/CodeGen/AArch64/GlobalISel/load-wro-addressing-modes.mir
llvm/test/CodeGen/AArch64/GlobalISel/opt-fold-ext-tbz-tbnz.mir
llvm/test/CodeGen/AArch64/GlobalISel/subreg-copy.mir
llvm/test/CodeGen/AArch64/GlobalISel/widen-narrow-tbz-tbnz.mir

aarch64: Some casting/shifting of __uint128_t hits an UNREACHABLE after regalloc in AArch64InstrInfo::copyPhysReg

---

llvm/lib/DebugInfo/DWARF/DWARFDebugArangeSet.cpp
llvm/unittests/DebugInfo/DWARF/DWARFDebugArangeSetTest.cpp

Although the DWARF specification states that .debug_aranges entries
can't have length zero, these can occur in the wild. There's no
particular reason to enforce this part of the spec, since functionally
they have no impact. The patch removes the error and introduces a new
warning for premature terminator entries which does not stop parsing.
This is a relanding of cb3a598c87db, adding the missing obj2yaml part
that was needed.
Fixes https://bugs.llvm.org/show_bug.cgi?id=46805. See also
https://reviews.llvm.org/D71932 which originally introduced the error.
Reviewed by: ikudrin, dblaikie, Higuoxing
Differential Revision: https://reviews.llvm.org/D85313
(cherry picked from commit ca05601cd2a1b75050538ef2e78de205f1300692)

Don't error for zero-length arange entries

---

llvm/cmake/modules/AddLLVM.cmake
llvm/include/llvm/Support/CMakeLists.txt

LLVM 11.0.0 always rebuilds due to VCS revision

---

clang/include/clang-c/Index.h
llvm/lib/Target/AArch64/GISel/AArch64LegalizerInfo.cpp
llvm/test/CodeGen/AArch64/GlobalISel/legalize-merge-values.mir
llvm/test/CodeGen/AArch64/GlobalISel/legalize-non-pow2-load-store.mir
llvm/test/CodeGen/AArch64/GlobalISel/legalize-shift.mir
llvm/test/CodeGen/AArch64/GlobalISel/legalize-unmerge-values.mir
llvm/test/CodeGen/AArch64/arm64-clrsb.ll

ABI compatibility of CXCursorKind broken

---

clang/lib/Basic/Targets/PPC.cpp
clang/test/CodeGen/builtins-ppc-fpconstrained.c
llvm/include/llvm/ADT/Any.h
llvm/include/llvm/IR/Constant.h
llvm/lib/Analysis/ConstantFolding.cpp
llvm/lib/IR/Constants.cpp
llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
llvm/lib/Transforms/Scalar/LowerConstantIntrinsics.cpp
llvm/test/Transforms/InstCombine/not-add.ll
llvm/test/Transforms/LowerConstantIntrinsics/constant-intrinsics.ll

Strict floating point is incompatible with SPE

---

clang-tools-extra/clangd/ConfigProvider.cpp
clang-tools-extra/clangd/GlobalCompilationDatabase.cpp
clang-tools-extra/clangd/TidyProvider.cpp
clang-tools-extra/clangd/support/Path.cpp
clang-tools-extra/clangd/support/Path.h

Cherry-pick 6329ce75da7a44c40d4406bf48ffffe973ef5fdb

---

libcxx/test/libcxx/gdb/gdb_pretty_printer_test.sh.cpp
libcxx/test/libcxx/memory/trivial_abi/unique_ptr_ret.pass.cpp
libcxx/test/libcxx/memory/trivial_abi/weak_ptr_ret.pass.cpp
llvm/include/llvm/ADT/Any.h
llvm/include/llvm/IR/Constant.h
llvm/lib/Analysis/ConstantFolding.cpp
llvm/lib/IR/Constants.cpp
llvm/lib/Transforms/InstCombine/InstCombineAndOrXor.cpp
llvm/lib/Transforms/Scalar/LowerConstantIntrinsics.cpp
llvm/test/Transforms/InstCombine/not-add.ll
llvm/test/Transforms/LowerConstantIntrinsics/constant-intrinsics.ll

libcxx/memory/trivial_abi/{unique,weak}_ptr_ret.pass.cpp tests fail on 32-bit x86

---

llvm/lib/Target/WebAssembly/WebAssemblyLowerEmscriptenEHSjLj.cpp
llvm/test/CodeGen/WebAssembly/lower-em-exceptions.ll

Issue 308 pr

---

llvm/lib/Target/BPF/BTFDebug.cpp
llvm/lib/Target/BPF/BTFDebug.h
llvm/test/CodeGen/BPF/BTF/extern-var-func-weak-section.ll
llvm/test/CodeGen/BPF/BTF/extern-var-section.ll
llvm/test/CodeGen/BPF/BTF/extern-var-weak-section.ll

Backport: "BPF: add extern func to data sections if specified"

---

llvm/lib/Target/BPF/BTFDebug.cpp
llvm/test/CodeGen/BPF/BTF/weak-global-3.ll

Backport: "BPF: generate proper BTF for globals with WeakODRLinkage"

---

llvm/lib/Analysis/ValueTracking.cpp

The current code can scan an unlimited number of instructions,
if the containing basic block is very large. The test case from
PR50155 contains a basic block with approximately 100k instructions.
To avoid this, limit the number of instructions we inspect. At
the same time, drop the limit on the number of basic blocks, as
this will be implicitly limited by the number of instructions as
well.
(cherry picked from commit 2cd78686055f1badb9aa55cb95e189548ffc82f0)

[ValueTracking] Limit scan when checking poison UB (PR50155)

---

clang-tools-extra/clangd/quality/CompletionModel.cmake

Merge f51ab187+7907c46f into 12.x

---

llvm/lib/Target/X86/X86InstrCompiler.td
llvm/test/CodeGen/X86/freeze.ll

Merge c997867dc084a1bcf631816f964b3ff49a297ba3 to 12.0.1

---

llvm/lib/Target/ARM/ARMBaseInstrInfo.cpp
llvm/test/CodeGen/ARM/machine-outliner-stack-fixup-thumb.mir

[ARM] Machine Outliner issue with LDRD/STRD in Thumb mode

---

llvm/lib/Target/PowerPC/PPCFrameLowering.cpp
llvm/lib/Target/PowerPC/PPCRegisterInfo.td
llvm/test/CodeGen/PowerPC/pr46759.ll
llvm/test/CodeGen/PowerPC/stack-clash-prologue-nounwind.ll
llvm/test/CodeGen/PowerPC/stack-clash-prologue.ll

Stack corruption with -fstack-clash-protection + -O2 on ppc64le with clang 12

---

clang/lib/Basic/Targets/X86.cpp

Please backport 092c303955cd18be6c0b923b1c0a1b96e2c91893 to 12.0.1

---

compiler-rt/lib/sanitizer_common/sanitizer_posix_libcdep.cpp

Backport 82150606fb11d28813ae6 into 12.0.1

---

libcxx/include/fstream

[libc++] Merge 52e9d80d5db20f23979e409f958736d130387f9e into 12.0.1

---

libcxx/include/memory
libcxx/test/std/utilities/memory/util.smartptr/util.smartptr.shared/util.smartptr.shared.assign/unique_ptr_Y.pass.cpp
libcxx/test/std/utilities/memory/util.smartptr/util.smartptr.shared/util.smartptr.shared.const/unique_ptr.pass.cpp

Cherry-pick 097d77d611d1e1b3972be661fdc3caaa4d1824b4 to release/12.x

---

clang/lib/CodeGen/CGExprAgg.cpp
clang/test/CodeGenCXX/trivial_abi.cpp

assertion failure converting lambda returning trivial_abi struct to function pointer

---

llvm/include/llvm/Support/Host.h
llvm/lib/Support/Host.cpp
llvm/tools/llvm-exegesis/lib/X86/Target.cpp

check-llvm with 12.0.0-rc1 takes very long while spawning llvm-exegesis

---

llvm/lib/Transforms/Coroutines/CoroEarly.cpp
llvm/lib/Transforms/Coroutines/CoroFrame.cpp
llvm/test/Transforms/Coroutines/coro-byval-param.ll
llvm/test/Transforms/Coroutines/coro-noalias-param.ll

Cherry-pick 3522167efd80e2fef42a865cdf7481d60d062603 to release/12.x

---

llvm/lib/Target/PowerPC/PPCISelLowering.cpp
llvm/test/CodeGen/PowerPC/inline-asm-physical-fpr-spe.ll
llvm/test/CodeGen/PowerPC/inline-asm-physical-fpr.ll

Backport: "[PowerPC] Handle FP physical register in inline asm constraint."

---

llvm/lib/Transforms/Scalar/DivRemPairs.cpp
llvm/test/Transforms/DivRemPairs/X86/div-expanded-rem-pair.ll

PR for #375

---

llvm/runtimes/CMakeLists.txt
openmp/libomptarget/tools/deviceinfo/CMakeLists.txt

PR for #383

---

llvm/lib/Analysis/TargetLibraryInfo.cpp
llvm/test/Transforms/InstCombine/simplify-libcalls.ll

PR for #385

---

llvm/include/llvm/Transforms/IPO/Attributor.h
llvm/lib/Transforms/IPO/Attributor.cpp
llvm/lib/Transforms/IPO/OpenMPOpt.cpp
llvm/test/Transforms/Attributor/internalize.ll
llvm/test/Transforms/OpenMP/custom_state_machines.ll

PR for #384

---

llvm/lib/Transforms/Scalar/SROA.cpp
llvm/test/Transforms/SROA/slice-width.ll

PR for #386

---

llvm/lib/Transforms/InstCombine/InstCombineLoadStoreAlloca.cpp
llvm/test/Transforms/InstCombine/memcpy-from-global.ll

PR for #390

---

compiler-rt/lib/profile/InstrProfilingPlatformLinux.c
llvm/test/tools/gold/X86/comdat-nodeduplicate.ll

PR for #406

---

clang/include/clang/Basic/LangOptions.h
clang/include/clang/Driver/Options.td
clang/include/clang/Lex/PreprocessorOptions.h
clang/lib/AST/Expr.cpp
clang/lib/Basic/LangOptions.cpp
clang/lib/CodeGen/CodeGenModule.cpp
clang/lib/Frontend/CompilerInvocation.cpp
clang/lib/Lex/PPMacroExpansion.cpp
clang/test/CodeGenCXX/builtin-source-location.cpp
llvm/test/tools/gold/X86/comdat-nodeduplicate.ll

PR for #405

---

openmp/runtime/src/kmp_taskdeps.cpp
openmp/runtime/src/kmp_taskdeps.h
openmp/runtime/test/tasking/kmp_taskwait_depend_in.c

PR for #398

---

clang-tools-extra/clang-tidy/bugprone/EasilySwappableParametersCheck.cpp
clang-tools-extra/test/clang-tidy/checkers/bugprone-easily-swappable-parameters-implicits.cpp
clang-tools-extra/test/clang-tidy/checkers/bugprone-easily-swappable-parameters-len2.cpp

PR for #399

---

llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp
llvm/test/Transforms/InstCombine/select-masked_load.ll

PR for #412

---

clang/tools/clang-repl/CMakeLists.txt

PR for #432

---

llvm/lib/Target/BPF/BPFTargetTransformInfo.h
llvm/test/CodeGen/BPF/loop-exit-cond.ll

PR for #434

---

llvm/utils/lit/tests/shtest-keyword-parse-errors.py

PR for #438

---

clang/lib/Driver/ToolChains/MinGW.cpp
clang/test/Driver/mingw.cpp

PR for #442

---

lld/MinGW/Options.td
lld/test/MinGW/driver.test

PR for #444

---

compiler-rt/CMakeLists.txt

PR for #445

---

openmp/runtime/src/kmp_tasking.cpp

PR for #447

---

mlir/lib/ExecutionEngine/CRunnerUtils.cpp

PR for #452

---

clang/lib/Driver/ToolChains/MinGW.cpp
clang/test/Driver/mingw.cpp
compiler-rt/CMakeLists.txt
flang/lib/Frontend/CMakeLists.txt
flang/lib/FrontendTool/CMakeLists.txt
flang/tools/flang-driver/CMakeLists.txt
flang/unittests/Frontend/CMakeLists.txt
lld/MinGW/Options.td
lld/test/MinGW/driver.test
mlir/lib/ExecutionEngine/CRunnerUtils.cpp
openmp/libomptarget/plugins/amdgpu/CMakeLists.txt
openmp/runtime/src/kmp_tasking.cpp

PR for #462

---

llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
llvm/test/CodeGen/AArch64/sve-fixed-length-masked-gather.ll
llvm/test/CodeGen/AArch64/sve-fixed-length-masked-scatter.ll

PR for #454

---

clang/lib/Driver/ToolChains/MinGW.cpp
clang/test/Driver/mingw.cpp
compiler-rt/CMakeLists.txt
flang/lib/Frontend/CMakeLists.txt
flang/lib/FrontendTool/CMakeLists.txt
flang/tools/flang-driver/CMakeLists.txt
flang/unittests/Frontend/CMakeLists.txt
lld/MinGW/Options.td
lld/test/MinGW/driver.test
lldb/test/Shell/Expr/nodefaultlib.cpp
lldb/test/Shell/lit.cfg.py
mlir/lib/ExecutionEngine/CRunnerUtils.cpp
openmp/runtime/src/kmp_tasking.cpp

PR for #457

---

clang/lib/Driver/ToolChains/MinGW.cpp
clang/test/Driver/mingw.cpp
compiler-rt/CMakeLists.txt
flang/lib/Frontend/CMakeLists.txt
flang/lib/FrontendTool/CMakeLists.txt
flang/tools/flang-driver/CMakeLists.txt
flang/unittests/Frontend/CMakeLists.txt
lld/MinGW/Options.td
lld/test/MinGW/driver.test
lldb/cmake/modules/LLDBStandalone.cmake
mlir/lib/ExecutionEngine/CRunnerUtils.cpp
openmp/runtime/src/kmp_tasking.cpp

PR for #456

---

llvm/lib/Target/RISCV/RISCVInstrInfoV.td
llvm/lib/Target/RISCV/RISCVSchedRocket.td
llvm/lib/Target/RISCV/RISCVSchedSiFive7.td
llvm/lib/Target/RISCV/RISCVSchedule.td
llvm/lib/Target/RISCV/RISCVScheduleV.td

PR for #411

---

llvm/lib/Transforms/IPO/Attributor.cpp
llvm/lib/Transforms/IPO/AttributorAttributes.cpp
llvm/test/Transforms/Attributor/value-simplify-pointer-info.ll

PR for #466

---

llvm/tools/llvm-mca/Views/TimelineView.cpp

PR for #468

---

libcxx/include/ios
libcxx/test/std/input.output/iostreams.base/ios/iostate.flags/bool.pass.cpp
lld/wasm/SyntheticSections.h

PR for #472

---

.github/workflows/release-workflow-close-issue.yml
clang-tools-extra/clang-tidy/cppcoreguidelines/InitVariablesCheck.cpp
clang-tools-extra/docs/ReleaseNotes.rst
clang-tools-extra/docs/clang-tidy/checks/cppcoreguidelines-init-variables.rst
clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines-init-variables.cpp

PR for #389

---

clang-tools-extra/clang-tidy/cppcoreguidelines/InitVariablesCheck.cpp
clang-tools-extra/docs/ReleaseNotes.rst
clang-tools-extra/docs/clang-tidy/checks/cppcoreguidelines-init-variables.rst
clang-tools-extra/test/clang-tidy/checkers/cppcoreguidelines-init-variables.cpp
llvm/lib/CodeGen/TargetLoweringObjectFileImpl.cpp

PR for #477

---

clang/lib/Driver/ToolChains/Clang.cpp

PR for #479

---

llvm/lib/Transforms/IPO/Attributor.cpp
llvm/test/Transforms/Attributor/value-simplify-pointer-info.ll

PR for #484

---

clang/lib/Driver/ToolChains/Hexagon.cpp
clang/test/Driver/hexagon-toolchain-linux.c

PR for #486

---

clang/lib/Sema/SemaTemplateInstantiate.cpp
clang/test/CXX/expr/expr.prim/expr.prim.req/type-requirement.cpp
clang/test/CXX/temp/temp.constr/temp.constr.normal/p1.cpp

PR for #437

---

clang/lib/Driver/ToolChains/Hexagon.cpp
clang/test/Driver/hexagon-toolchain-linux.c

PR for #488

---

lld/MinGW/Driver.cpp
lld/MinGW/Options.td
lld/test/MinGW/driver.test

PR for #492

---

llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp
llvm/test/CodeGen/AArch64/sve-fixed-length-masked-scatter.ll

PR for #493

---

clang/lib/Driver/ToolChains/Hexagon.cpp
clang/lib/Sema/SemaTemplateInstantiate.cpp
clang/test/CXX/expr/expr.prim/expr.prim.req/type-requirement.cpp
clang/test/CXX/temp/temp.constr/temp.constr.normal/p1.cpp
clang/test/Driver/hexagon-toolchain-linux.c
flang/runtime/time-intrinsic.cpp
lld/MinGW/Driver.cpp
lld/MinGW/Options.td
lld/test/MinGW/driver.test
llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp
llvm/test/CodeGen/AArch64/sve-fixed-length-masked-scatter.ll

PR for #503

---

llvm/lib/Target/X86/X86ISelLowering.cpp
llvm/test/CodeGen/X86/pr51281.ll

PR for #490

---

compiler-rt/lib/profile/InstrProfilingPlatformLinux.c

PR for #471

---

compiler-rt/lib/scudo/standalone/tests/CMakeLists.txt

PR for #516

---

compiler-rt/lib/profile/CMakeLists.txt
compiler-rt/lib/profile/InstrProfilingFile.c

PR for #502

---

llvm/test/tools/llvm-cov/branch-export-lcov.test
llvm/tools/llvm-cov/CoverageExporterLcov.cpp

PR for #517

---

llvm/lib/Target/M68k/AsmParser/M68kAsmParser.cpp

PR for #531

---

clang/lib/Basic/Targets/M68k.cpp
llvm/lib/Target/M68k/AsmParser/M68kAsmParser.cpp
llvm/lib/Target/M68k/M68kTargetMachine.cpp

PR for #537

---

llvm/lib/CodeGen/SelectionDAG/LegalizeIntegerTypes.cpp
llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp
llvm/lib/Target/M68k/AsmParser/M68kAsmParser.cpp
llvm/test/CodeGen/X86/smul_fix_sat.ll
llvm/test/CodeGen/X86/smul_fix_sat_constants.ll

PR for #539

---

compiler-rt/lib/profile/InstrProfilingPlatformLinux.c

PR for #529

---

llvm/lib/Transforms/Scalar/AlignmentFromAssumptions.cpp
llvm/test/Transforms/AlignmentFromAssumptions/simple.ll

PR for #543

---

llvm/lib/Passes/PassBuilder.cpp
llvm/test/Other/new-pm-lto-defaults.ll

PR for #546

---

clang/lib/AST/ASTContext.cpp
clang/test/AST/ast-dump-openmp-begin-declare-variant_reference.cpp

PR for #547

---

llvm/lib/Linker/LinkModules.cpp
llvm/test/Linker/comdat4.ll

PR for #550

---

llvm/test/ExecutionEngine/OrcLazy/debug-descriptor-elf-minimal.ll
llvm/test/ExecutionEngine/OrcLazy/debug-objects-elf-minimal.ll

PR for #552

---

llvm/runtimes/CMakeLists.txt
openmp/libomptarget/DeviceRTL/CMakeLists.txt
openmp/libomptarget/deviceRTLs/amdgcn/CMakeLists.txt

PR for #544

---

clang/lib/Driver/ToolChains/OpenBSD.cpp

PR for #562

---

clang/lib/Driver/ToolChains/CommonArgs.cpp

PR for #563

---

clang/lib/Driver/ToolChains/OpenBSD.cpp
clang/test/Driver/fopenmp.c

PR for #564

---

clang/lib/Sema/SemaTemplateInstantiateDecl.cpp
clang/test/CXX/class/class.init/class.copy.elision/p3.cpp

PR for #558

---

clang/lib/Serialization/ASTReader.cpp

PR for #560

---

clang/lib/Basic/Targets/OSTargets.h
clang/test/Preprocessor/init.c

PR for #565

---

llvm/lib/Analysis/ScalarEvolution.cpp
llvm/test/Analysis/ScalarEvolution/max-backedge-taken-count-guard-info.ll

PR for #573

---

libunwind/src/Unwind-EHABI.cpp

PR for #576

---

compiler-rt/lib/profile/InstrProfilingFile.c
compiler-rt/lib/profile/InstrProfilingPlatformFuchsia.c

PR for #532

---

clang/lib/Driver/Driver.cpp
clang/unittests/Driver/ToolChainTest.cpp

PR for #570

---

llvm/cmake/modules/AddLLVM.cmake

PR for #584

---

llvm/test/tools/llvm-objdump/X86/elf-disassemble-relocs-exec.test
llvm/tools/llvm-objdump/llvm-objdump.cpp

PR for #582

---

llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp
llvm/test/CodeGen/X86/20210831-inlineasm.ll

PR for #585

---

clang/lib/Sema/TreeTransform.h
clang/test/CXX/dcl/dcl.spec/dcl.type/dcl.spec.auto/p6.cpp

PR for #583

---

llvm/include/llvm/Analysis/TargetTransformInfo.h
llvm/lib/Analysis/TargetTransformInfo.cpp
llvm/lib/CodeGen/HardwareLoops.cpp
llvm/test/CodeGen/PowerPC/loop-instr-prep-non-const-increasement.ll
llvm/test/CodeGen/PowerPC/mma-phi-accs.ll

PR for #592

---

llvm/lib/Target/AArch64/SMEInstrFormats.td
llvm/test/MC/AArch64/SME/mova-diagnostics.s

PR for #593

---

llvm/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp
llvm/test/Transforms/SimpleLoopUnswitch/nontrivial-unswitch-markloopasdeleted.ll

PR for #571

---

llvm/lib/Target/AArch64/AArch64ISelLowering.cpp
llvm/test/CodeGen/AArch64/sve-fixed-length-masked-gather.ll
llvm/test/CodeGen/AArch64/sve-fixed-length-masked-scatter.ll

PR for #554

---

clang/lib/Headers/openmp_wrappers/complex
clang/test/Headers/amdgcn-openmp-device-math-complex.cpp

PR for #600

---

clang/lib/Format/TokenAnnotator.cpp
clang/lib/Format/UnwrappedLineParser.cpp
clang/unittests/Format/FormatTest.cpp

PR for #591

---

compiler-rt/lib/scudo/standalone/CMakeLists.txt

PR for #602

---

llvm/lib/Transforms/Utils/SimplifyCFG.cpp
llvm/test/CodeGen/Thumb2/mve-float16regloops.ll
llvm/test/CodeGen/Thumb2/mve-float32regloops.ll
llvm/test/CodeGen/Thumb2/mve-postinc-lsr.ll
llvm/test/Transforms/LoopUnroll/peel-loop-inner.ll
llvm/test/Transforms/PhaseOrdering/X86/vector-reductions-logical.ll
llvm/test/Transforms/SimplifyCFG/fold-branch-to-common-dest.ll

PR for #604

---

llvm/lib/IR/Constants.cpp
llvm/test/Transforms/InstSimplify/ConstProp/vecreduce.ll

PR for #608

---

lld/ELF/InputSection.cpp
lld/ELF/InputSection.h
lld/test/ELF/compressed-debug-input-err.s
lld/test/ELF/compressed-debug-input.s

PR for #609

---

lld/test/ELF/compressed-debug-input-err.s
lld/test/ELF/compressed-debug-input.s

PR for #638

---

compiler-rt/lib/builtins/clear_cache.c

PR for #642

---

clang/tools/scan-build/libexec/ccc-analyzer

PR for #641

---

llvm/lib/Target/X86/X86ISelLowering.cpp
llvm/test/CodeGen/X86/vector-reduce-mul.ll

PR for #637

---

clang/test/Driver/rocm-detect.hip

PR for #651

---

.github/workflows/clang-tests.yml
.github/workflows/libclang-abi-tests.yml
.github/workflows/libclc-tests.yml
.github/workflows/lld-tests.yml
.github/workflows/lldb-tests.yml
.github/workflows/llvm-tests.yml
.github/workflows/release-workflow-close-issue.yml
clang/lib/Format/TokenAnnotator.cpp
clang/lib/Format/UnwrappedLineParser.cpp
clang/unittests/Format/FormatTest.cpp
clang/unittests/Format/FormatTestCSharp.cpp

PR for #536

---

llvm/lib/CodeGen/DwarfEHPrepare.cpp
llvm/lib/Target/ARM/ARMInstrThumb.td
llvm/lib/Target/ARM/ARMInstrThumb2.td
llvm/test/CodeGen/ARM/readtp.ll
llvm/test/CodeGen/ARM/thread_pointer.ll
llvm/test/CodeGen/X86/dwarf-eh-prepare.ll

PR for #682

---

clang/lib/Basic/Targets/OSTargets.h
clang/test/Preprocessor/init.c
llvm/lib/CodeGen/DwarfEHPrepare.cpp
llvm/test/CodeGen/X86/dwarf-eh-prepare.ll

PR for #684

---

llvm/lib/CodeGen/DwarfEHPrepare.cpp
llvm/test/CodeGen/X86/dwarf-eh-prepare.ll
mlir/CMakeLists.txt

PR for #686

---

clang/lib/Basic/Targets/OSTargets.h
clang/test/Preprocessor/init.c
libcxx/docs/ReleaseNotes.rst
libcxx/include/__threading_support
libcxx/include/semaphore
libcxx/src/support/win32/thread_win32.cpp
libcxx/test/std/thread/thread.semaphore/acquire.pass.cpp
libcxx/test/std/thread/thread.semaphore/binary.pass.cpp
libcxx/test/std/thread/thread.semaphore/ctor.compile.pass.cpp
libcxx/test/std/thread/thread.semaphore/max.pass.cpp
libcxx/test/std/thread/thread.semaphore/release.pass.cpp
libcxx/test/std/thread/thread.semaphore/try_acquire.pass.cpp
llvm/lib/CodeGen/DwarfEHPrepare.cpp
llvm/lib/Target/AMDGPU/SILoadStoreOptimizer.cpp
llvm/lib/Target/ARM/ARMInstrThumb.td
llvm/lib/Target/ARM/ARMInstrThumb2.td
llvm/test/CodeGen/ARM/readtp.ll
llvm/test/CodeGen/ARM/thread_pointer.ll
llvm/test/CodeGen/X86/dwarf-eh-prepare.ll
mlir/CMakeLists.txt

PR for #688

---

llvm/lib/Target/AArch64/AArch64ExpandPseudoInsts.cpp
llvm/lib/Target/AArch64/AArch64InstrInfo.td
llvm/test/CodeGen/AArch64/GlobalISel/select-add-low.mir
llvm/test/CodeGen/AArch64/GlobalISel/select-blockaddress.mir
llvm/test/CodeGen/AArch64/GlobalISel/select-gv-with-offset.mir
llvm/test/CodeGen/AArch64/GlobalISel/select-jump-table-brjt-constrain.mir
llvm/test/CodeGen/AArch64/GlobalISel/select-jump-table-brjt.mir
llvm/test/CodeGen/AArch64/GlobalISel/select-static.mir
llvm/test/CodeGen/AArch64/GlobalISel/select.mir
llvm/test/CodeGen/AArch64/elim-dead-mi.mir
llvm/test/CodeGen/AArch64/loop-sink.mir

PR for #676

---

llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp
llvm/test/Transforms/SLPVectorizer/X86/extract_in_tree_user.ll

PR for #693

---

llvm/lib/Target/SystemZ/SystemZInstrInfo.td

PR for #690

---

lld/ELF/InputFiles.cpp
lld/test/ELF/allow-shlib-undefined-weak.s

PR for #701

---

clang/lib/Analysis/UninitializedValues.cpp
clang/test/Analysis/uninit-asm-goto.cpp
libcxx/include/string
libcxx/test/std/strings/basic.string/string.capacity/shrink_to_fit.explicit_instantiation.sh.cpp
lld/ELF/InputFiles.cpp
lld/test/ELF/allow-shlib-undefined-weak.s

PR for #702

---

llvm/include/llvm/Support/Parallel.h
llvm/lib/Support/Parallel.cpp

PR for #715

---

llvm/lib/Target/PowerPC/AsmParser/PPCAsmParser.cpp
llvm/test/CodeGen/PowerPC/inline-asm-label.ll
llvm/test/MC/PowerPC/ppc64-encoding-bookII.s
llvm/test/MC/PowerPC/ppc64-errors.s

PR for #718

---

llvm/lib/Transforms/Utils/RelLookupTableConverter.cpp
llvm/test/Transforms/RelLookupTableConverter/X86/relative_lookup_table.ll

PR for #719

---

compiler-rt/lib/asan/asan_malloc_linux.cpp

PR for #735

---

clang/lib/Basic/Targets/Sparc.h
clang/test/Sema/builtin-longjmp.c

PR for #729

---

compiler-rt/test/lit.common.cfg.py
compiler-rt/test/msan/preinit_array.cpp

PR for #742

---

compiler-rt/test/asan/TestCases/Posix/unpoison-alternate-stack.cpp

PR for #749

---

compiler-rt/test/sanitizer_common/TestCases/Linux/pthread_mutex.cpp

PR for #746

---

compiler-rt/test/lit.common.cfg.py
compiler-rt/test/msan/preinit_array.cpp
lld/ELF/Arch/PPC.cpp

PR for #755

---

llvm/lib/Analysis/AliasAnalysis.cpp
llvm/test/Analysis/BasicAA/pr52735.ll

PR for #741

---

compiler-rt/test/sanitizer_common/TestCases/Linux/sysconf_interceptor_bypass_test.cpp

PR for #748

---

llvm/lib/IR/LLVMContextImpl.h
llvm/unittests/IR/DebugInfoTest.cpp

PR for #757

---

clang/lib/Driver/ToolChains/Arch/AArch64.cpp
clang/test/Driver/aarch64-target-as-march.s

PR for #728

---

llvm/include/llvm/CodeGen/TargetInstrInfo.h
llvm/lib/CodeGen/TargetInstrInfo.cpp
llvm/lib/Target/AArch64/AArch64InstrInfo.cpp
llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
llvm/test/CodeGen/AArch64/machine-outliner-patchable.ll
llvm/test/CodeGen/RISCV/machine-outliner-patchable.ll

PR for #711

---

llvm/include/llvm/IR/Metadata.h
llvm/lib/CodeGen/RegAllocFast.cpp
llvm/lib/IR/DebugInfoMetadata.cpp
llvm/lib/IR/LLVMContextImpl.cpp

PR for #733

---

clang/lib/Analysis/CFG.cpp
clang/lib/Analysis/UninitializedValues.cpp
clang/test/Analysis/asm-goto.cpp
clang/test/Analysis/uninit-asm-goto.cpp
clang/test/Sema/array-bounds-ptr-arith.c

resolves tstellar/llvm-project#778

PR for tstellar/llvm-project#778

---

clang/lib/Sema/SemaExpr.cpp
clang/test/SemaCXX/varargs.cpp

resolves tstellar/llvm-project#779

PR for tstellar/llvm-project#779

---

llvm/lib/Target/ARM/ARMCallLowering.cpp
llvm/lib/Target/ARM/ARMFastISel.cpp
llvm/test/CodeGen/ARM/GlobalISel/arm-call-lowering.ll
llvm/test/CodeGen/ARM/GlobalISel/arm-param-lowering.ll
llvm/test/CodeGen/ARM/GlobalISel/irtranslator-varargs-lowering.ll
llvm/test/CodeGen/ARM/fast-call-frame-restore.ll

resolves tstellar/llvm-project#773

PR for tstellar/llvm-project#773

---

llvm/lib/Analysis/InlineCost.cpp
llvm/test/Transforms/Inline/call-intrinsic-is-constant.ll

resolves tstellar/llvm-project#772

PR for tstellar/llvm-project#772

---

llvm/lib/Transforms/Coroutines/CoroSplit.cpp
llvm/test/Transforms/Coroutines/coro-split-musttail4.ll

resolves tstellar/llvm-project#785

PR for tstellar/llvm-project#785

---

clang/test/Driver/undefined-libs.cpp

resolves tstellar/llvm-project#794

PR for tstellar/llvm-project#794

---

llvm/lib/Target/ARM/ARMISelDAGToDAG.cpp
llvm/test/CodeGen/ARM/shifter_operand.ll

resolves tstellar/llvm-project#795

PR for tstellar/llvm-project#795
