tstellar/llvm-project

- clang/lib/CodeGen/CGVTables.cpp
- clang/test/CodeGenCXX/ms-thunks-ehspec.cpp
- clang/test/CodeGenCXX/thunks-ehspec.cpp
> CGCleanup.h:583: void clang::CodeGen::EHScopeStack::popTerminate(): Assertion `!empty() && "popping exception stack when not empty"' failed

- lld/COFF/MarkLive.cpp
- lld/test/COFF/gc-dwarf.s
> DWARF breaks garbage collection in PE/COFF

- clang/docs/ReleaseNotes.rst
> Release note: `-ffp-exception-behavior=<value>` in llvm 10.0

- llvm/lib/Target/PowerPC/PPCISelLowering.cpp
- llvm/test/CodeGen/PowerPC/kernel-fp-round.ll
In LowerFP_TO_INTForReuse, when emitting `stfiwx`, alignment of 4 is
set for the `MachineMemOperand`, but RLI(ReuseLoadInfo)'s alignment is
not updated for following loads.
It's related to failed alignment check reported in
https://bugs.llvm.org/show_bug.cgi?id=45297
Differential Revision: https://reviews.llvm.org/D77624
Backport b7d5229d789b7cb2747226d528ed016624b11cea.
> [PowerPC] Update alignment for ReuseLoadInfo in LowerFP_TO_INTForReuse

- clang/lib/Driver/ToolChains/Gnu.cpp
- clang/lib/Driver/ToolChains/Gnu.h
- clang/lib/Driver/ToolChains/Hurd.cpp
- clang/lib/Driver/ToolChains/Hurd.h
- clang/lib/Driver/ToolChains/Linux.cpp
- clang/lib/Driver/ToolChains/Linux.h
> [Clang] Fix Hurd toolchain test on a two-stage build with ThinLTO

- lldb/source/Plugins/ObjectFile/PECOFF/ObjectFilePECOFF.cpp
> Backport D77000, "[lldb] [PECOFF] Only use PECallFrameInfo on the one supported architecture", to 10.0.1

- clang/lib/AST/ExprConstant.cpp
- clang/test/SemaCXX/constant-expression-cxx2a.cpp
of array new expressions with runtime bound.
(cherry picked from commit 9a7eda1bece887ca9af085d79fe6e4fb8826dcda)
> PR45350: Handle unsized array CXXConstructExprs in constant evaluation

- .github/workflows/llvm-tests.yml
- llvm/lib/Transforms/IPO/GlobalOpt.cpp
- llvm/test/DebugInfo/Generic/global-sra-struct-zero-length.ll
of a struct that cover the whole struct
This can happen when the rest of the
members of are zero length. Following
the same pattern applied to the SROA
pass in:
d7f6f1636d53c3e2faf55cdf20fbb44a1a149df1
Fixes: https://bugs.llvm.org/show_bug.cgi?id=45335
Differential Revision: https://reviews.llvm.org/D78720
> [globalopt] Don't emit DWARF fragments for members

- llvm/utils/lit/lit/formats/googletest.py
> Please backport 88aad9b9f05 (lit googletest.py: Don't raise StopIteration in generator) to 10.x

- llvm/lib/Transforms/Scalar/IndVarSimplify.cpp
- llvm/test/Transforms/IndVarSimplify/pr45835.ll
Summary:
Currently, `rewriteLoopExitValues()`'s logic is roughly as following:
> Loop over each incoming value in each PHI node.
> Query whether the SCEV for that incoming value is high-cost.
> Expand the SCEV.
> Perform sanity check (`isValidRewrite()`, D51582)
> Record the info
> Afterwards, see if we can drop the loop given replacements.
> Maybe perform replacements.
The problem is that we interleave SCEV cost checking and expansion.
This is A Problem, because `isHighCostExpansion()` takes special care
to not bill for the expansions that were already expanded, and we can reuse.
While it makes sense in general - if we know that we will expand some SCEV,
all the other SCEV's costs should account for that, which might cause
some of them to become non-high-cost too, and cause chain …
> [IndVarSimplify][LoopUtils] Avoid TOCTOU/ordering issues (PR45835)

- clang/test/Driver/aarch64-cpus.c
- llvm/include/llvm/Support/AArch64TargetParser.def
- llvm/lib/Target/AArch64/AArch64.td
- llvm/lib/Target/AArch64/AArch64SchedA53.td
- llvm/lib/Target/AArch64/AArch64SchedA57.td
- llvm/lib/Target/AArch64/AArch64SchedCyclone.td
- llvm/lib/Target/AArch64/AArch64SchedExynosM3.td
- llvm/lib/Target/AArch64/AArch64SchedExynosM4.td
- llvm/lib/Target/AArch64/AArch64SchedExynosM5.td
- llvm/lib/Target/AArch64/AArch64SchedFalkor.td
- llvm/lib/Target/AArch64/AArch64SchedKryo.td
- llvm/lib/Target/AArch64/AArch64SchedThunderX.td
- llvm/lib/Target/AArch64/AArch64SchedThunderX2T99.td
- llvm/lib/Target/AArch64/AArch64SchedThunderX3T110.td
- llvm/lib/Target/AArch64/AArch64Subtarget.cpp
- llvm/lib/Target/AArch64/AArch64Subtarget.h
- llvm/test/CodeGen/AArch64/aarch64-combine-fmul-fsub.mir
- llvm/test/CodeGen/AArch64/cpus.ll
- llvm/test/CodeGen/AArch64/machine-combiner-madd.ll
- llvm/test/CodeGen/AArch64/preferred-function-alignment.ll
- llvm/test/CodeGen/AArch64/remat.ll
- llvm/unittests/Support/TargetParserTest.cpp
This is the first checkin to support Marvell ThunderX3T110.
Initial definition of the micro-ops of the instructions in ThunderX3T110
is included.
Differential Revision: https://reviews.llvm.org/D78129
(cherry picked from commit 382d3a85e2a9269569e7fb8caa487d7ef57900c6)
> [AARch64] Add Marvell ThunderX3T110 support

- lld/COFF/Chunks.h
- lld/COFF/DLL.cpp
- lld/test/COFF/arm64-import2.test
The alignment of ARM64 range extension thunks was fixed in
7c816492197a, but ARM range extension thunks, and import
and delay import thunks also need aligning (like all code on ARM
platforms).
I'm adding a test for alignment of ARM64 import thunks - not
specifically adding tests for misalignment of all of them though.
Differential Revision: https://reviews.llvm.org/D77796
(cherry picked from commit 12c9e2f1110a4fc73562214cf5dd0194b31e87cf)
> Fix alignment of thunks for ARM/ARM64

- llvm/include/llvm/Target/TargetSelectionDAG.td
- llvm/lib/Target/PowerPC/PPCISelLowering.cpp
- llvm/lib/Target/PowerPC/PPCISelLowering.h
- llvm/lib/Target/PowerPC/PPCInstrVSX.td
- llvm/test/CodeGen/PowerPC/scalar_vector_test_2.ll
- llvm/test/CodeGen/PowerPC/vector-constrained-fp-intrinsics.ll
The fix for PR39865 took care of some of the handling for half precision
but it missed a number of issues that still exist. This patch fixes the
remaining issues that cause crashes in the PPC back end.
Fixes: https://bugs.llvm.org/show_bug.cgi?id=45776
Differential revision: https://reviews.llvm.org/D79283
(cherry picked from commit 1a493b0fa556a07c728862c3c3f70bfd8683bef0)
> [PowerPC] Add missing handling for half precision

- llvm/lib/Analysis/BasicAliasAnalysis.cpp
- llvm/test/Analysis/BasicAA/phi-values-usage.ll
- llvm/test/Other/opt-O2-pipeline.ll
- llvm/test/Other/opt-O3-pipeline.ll
- llvm/test/Other/opt-Os-pipeline.ll
Summary:
Part of the changes in D44564 made BasicAA not CFG only due to it using
PhiAnalysisValues which may have values invalidated.
Subsequent patches (rL340613) appear to have addressed this limitation.
BasicAA should not be invalidated by non-CFG-altering passes.
A concrete example is MemCpyOpt which preserves CFG, but we are testing
it invalidates BasicAA.
llvm-dev RFC: https://groups.google.com/forum/#!topic/llvm-dev/eSPXuWnNfzM
Reviewers: john.brawn, sebpop, hfinkel, brzycki
Subscribers: hiraditya, llvm-commits
Tags: #llvm
Differential Revision: https://reviews.llvm.org/D74353
(cherry picked from commit 0cecafd647ccd9d0acc5968d4d6e80c1cbdee275)
> [BasicAA] Make BasicAA a cfg pass.

- compiler-rt/test/profile/Inputs/instrprof-gcov-multithread_fork.cpp
Summary:
Patch in D78477 introduced a new test for gcov and this test is failing on arm:
- http://lab.llvm.org:8011/builders/clang-cmake-thumbv7-full-sh/builds/4752/steps/ninja%20check%202/logs/stdio
- http://lab.llvm.org:8011/builders/clang-cmake-armv7-full/builds/10501/steps/ninja%20check%202/logs/stdio
So try to fix it in reducing the number of threads.
Reviewers: marco-c
Reviewed By: marco-c
Subscribers: dberris, kristof.beyls, #sanitizers, serge-sans-paille, sylvestre.ledru
Tags: #sanitizers
Differential Revision: https://reviews.llvm.org/D79621
(cherry picked from commit 0da37bedc2667da371eda30595a06210595881d0)
> [compiler-rt] Reduce the number of threads in gcov test to avoid failure

- llvm/include/llvm/Support/ManagedStatic.h
> LLVM's ManagedStatic.h fails with VS 2019 <atomic> and clang-cl due to init-order-fiasco and constexpr confusion

- llvm/lib/Transforms/InstCombine/InstCombineAddSub.cpp
- llvm/test/Transforms/InstCombine/abs-1.ll
PR45539:
https://bugs.llvm.org/show_bug.cgi?id=45539
(cherry picked from commit 01bcc3e9371470e1974f066ced353df15e10056d)
> [InstCombine] prevent infinite loop with sub/abs of constant expression

- llvm/lib/Target/PowerPC/PPCAsmPrinter.cpp
- llvm/test/CodeGen/PowerPC/inlineasm-output-template.ll
Summary:
L is meant to support the second word used by 32b calling conventions for 64b arguments.
This is required for build 32b PowerPC Linux kernels after upstream
commit 334710b1496a ("powerpc/uaccess: Implement unsafe_put_user() using 'asm goto'")
Thanks for the report from @nathanchance, and reference to GCC's
implementation from @segher.
Fixes: pr/46186
Fixes: https://github.com/ClangBuiltLinux/linux/issues/1044
Reviewers: echristo, hfinkel, MaskRay
Reviewed By: MaskRay
Subscribers: MaskRay, wuzish, nemanjai, hiraditya, kbarton, steven.zhang, llvm-commits, segher, nathanchance, srhines
Tags: #llvm
Differential Revision: https://reviews.llvm.org/D81767
(cherry picked from commit 2d8e105db6bea10a6b96e4a094e73a87987ef909)
> [PPCAsmPrinter] support 'L' output template for memory operands

- llvm/lib/Target/AArch64/GISel/AArch64RegisterBankInfo.cpp
- llvm/test/CodeGen/AArch64/GlobalISel/regbankselect-default.mir
> Please backport e887d0e89b8 (refs/bisect/new) [AArch64][GlobalISel] Handle rtcGPR64RegClassID in AArch64RegisterBankInfo::getRegBankFromRegClass()

- llvm/lib/Target/WebAssembly/WebAssemblyFastISel.cpp
- llvm/test/CodeGen/WebAssembly/fast-isel-pr47040.ll
> Merge cc612c29084e907900ce63ad9031ab573a64e942 into 11.0.1: [WebAssembly] Fix FastISel address calculation bug

- llvm/lib/Target/AMDGPU/SIPreEmitPeephole.cpp
- llvm/test/CodeGen/AMDGPU/transform-block-with-return-to-epilog.ll
SIPreEmitPeephole does not process all terminators, which means
it can fail to handle SI_RETURN_TO_EPILOG if immediately preceeded
by a branch to the early exit block.
Reviewed By: rampitec
Differential Revision: https://reviews.llvm.org/D85872
(cherry picked from commit d538c5837a2cfedbf274133e29612da76003beed)
> Fix missed SI_RETURN_TO_EPILOG in pre-emit peephole

- llvm/lib/MC/MCParser/ELFAsmParser.cpp
- llvm/test/MC/ELF/section-flags-changed.s
- llvm/test/MC/ELF/section-omitted-attributes.s
> [LLVM 11 regression] MC assembler check, rejects common assembler code as, e.g., generated by GCC

- llvm/lib/Support/Windows/Path.inc
> Backport 79657e2: Avoid setting the delete-on-close bit if a TempFil… …e doesn't reside on a local drive

- clang/lib/Headers/ppc_wrappers/xmmintrin.h
- clang/test/CodeGen/ppc-xmmintrin.c
> PPC SSE emulation wrappers don't work in C++ mode

- llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp
- llvm/test/CodeGen/X86/stores-merging.ll
> Overly optimized simultaneous copy of struct fields corrupts destination struct

- openmp/libomptarget/src/interface.cpp
> [OpenMP] Fix typo in libomptarge for the wrong environment variable

- llvm/lib/Transforms/IPO/ConstantMerge.cpp
- llvm/test/Transforms/ConstantMerge/dont-merge.ll
> ConstantMerge drops thread_local from global

- llvm/include/llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h
- llvm/lib/DebugInfo/DWARF/DWARFDie.cpp
- llvm/lib/DebugInfo/DWARF/DWARFFormValue.cpp
- llvm/test/DebugInfo/implicit-const-test2.s
> Backport: "llvm-dwarfdump: Fix DWARF-5 DW_FORM_implicit_const (used by GCC)"
